#默认使用配置
spring:
  profiles:
    active: dev
#公共配置与profiles选择无关
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.app.*.model
server:
  port: 8008
---

#开发配置
spring:
  profiles: dev

#  data:
#    mongodb:
#      host: localhost
#      port: 1111
#      username: 111
#      password: 111
#      database: liulinfa

  datasource:
    url: jdbc:mysql://localhost:3306/ben?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #配置初始化大小/最小/最大
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    filters: stat,wall,log4j
    logSlowSql: true

#  data:
#    mongodb:
##        host: 47.107.87.11 # mongodb host
##        port: 27017 # mongodb port
##        username: root # mongodb username admin:jinzhuan2013; autorp:jz1005linux27017Mdb
##        password: root=-974=##!abc # mongodb password
##        authenticationDatabase: admin
#        uri: mongodb://liulinfa:123456@localhost:27017/test # mongodb authentication database


#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#swagger
sop:
  swagger:
        host: 47.101.163.185/bsapi
#      host: localhost:8008
# 上传图片路径
qiniu:
  accessKey: Sx5EFM1IAFjXmKZoZKRKGXfvvindt3_vVkI-irl1
  secretKey: 1e-uMDlF-tZ-wSp8QsCH9wCkIMyctOhLp1HbXplv
  bucket: linfaliu
  path: pjkoq6nhq.bkt.clouddn.com


#druid监控配置
druid:
  user-mapping: /druid/*
  # 禁用HTML页面上的“Rest All”功能
  reset-enable: false
  # ip白名单（没有配置或者为空，则允许所有访问）
  allow: ""
  # 监控页面登录用户名
  login-username: ben
  # 监控页面登录用户密码
  login-password: liulinfa
  #ip黑名单, 如果某个ip同时存在，deny优先于allow
  deny: ""
  #exclusions值不能以*开头
  exclusions: /druid/*,*.js,*.css